version: "3.9"
services:
  # MongoDB container
  mongo_db:
    container_name: mongo_c
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_DATABASE=mongo-db-tanduhm
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_db:/data/db
    restart: always

  # API service
  api:
    build: .
    container_name: api_c
    ports:
      - '4000:4000'
    environment:
      MONGODB_URI: mongodb://mongo_c:27017
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo_db

#docker back up the db
volumes:
  mongo_db: {}
  # mongo_express:
  #   image: mongo-express:latest
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_SERVER=mongo-db
